### ISSUE TITLE
Possible ARM container version

### ISSUE THREAD

**Issue by BenB196** [jlesage/docker-crashplan-enterprise#2] opened 2019-03-13 20:46 UTC
It would be nice to have an ARM version of this container. Would you possibly be able to make one, if not could you provide the steps you took to make the initial container, and I can try my hand at creating one.

**Comment by jlesage** [comment] 2019-03-14 02:25
The problem is that there is no CrashPlan binaries for ARM...

**Comment by BenB196** [comment] 2019-03-14 14:56
I think that since the actual Crashplan client is Java based, if you build the container with Debian packages, in theory it should work. A really old post http://www.jonrogers.co.uk/2012/05/crashplan-on-the-raspberry-pi/ seems to just suggest this.

**Comment by jlesage** [comment] 2019-03-14 23:35
It's true that few years ago, CrashPlan was 100% java based.  Today, only the engine is in Java.  The UI is no longer a Java application.
Also, at some point, it was possible to run the engine on a machine and the UI on another.  But this is also no longer possible/supported...

**Comment by jlesage** [comment] 2022-10-29 20:32
Closing this issue.

**Closed by jlesage** 2022-10-29 20:32 UTC
